//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 11:05:26 ip. EEST 
//


package huju.mcu.schemas;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DataUpdate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataUpdate">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *       &lt;attribute name="dbStoreInterval" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="cacheUpdatateInterval" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataUpdate", propOrder = {
    "value"
})
public class DataUpdate {

    @XmlValue
    protected boolean value;
    @XmlAttribute
    protected BigInteger dbStoreInterval;
    @XmlAttribute
    protected BigInteger cacheUpdatateInterval;

    /**
     * Gets the value of the value property.
     * 
     */
    public boolean isValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(boolean value) {
        this.value = value;
    }

    /**
     * Gets the value of the dbStoreInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDbStoreInterval() {
        return dbStoreInterval;
    }

    /**
     * Sets the value of the dbStoreInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDbStoreInterval(BigInteger value) {
        this.dbStoreInterval = value;
    }

    /**
     * Gets the value of the cacheUpdatateInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCacheUpdatateInterval() {
        return cacheUpdatateInterval;
    }

    /**
     * Sets the value of the cacheUpdatateInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCacheUpdatateInterval(BigInteger value) {
        this.cacheUpdatateInterval = value;
    }

}
