//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 12:11:23 ap. EEST 
//


package huju.mcu.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the huju.mcu.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: huju.mcu.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DisplayData }
     * 
     */
    public DisplayData createDisplayData() {
        return new DisplayData();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Devices }
     * 
     */
    public Devices createDevices() {
        return new Devices();
    }

    /**
     * Create an instance of {@link DataUpdate }
     * 
     */
    public DataUpdate createDataUpdate() {
        return new DataUpdate();
    }

    /**
     * Create an instance of {@link DataFilter }
     * 
     */
    public DataFilter createDataFilter() {
        return new DataFilter();
    }

    /**
     * Create an instance of {@link DisplayElement }
     * 
     */
    public DisplayElement createDisplayElement() {
        return new DisplayElement();
    }

}
