//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 12:11:23 ap. EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vuomokki.dyndns.tv/mcuschemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package huju.mcu.schemas;
