#ifndef MCUDATATYPES_H_
#define HIH-MCUDATATYPES_H_


enum DataType
{	
	UNDEFINED = 0,
	COMMAND_REQUEST = 1,
	COMMAND_RESPONSE = 2,
	TIMED_READING = 3,
	TRIGGERED_DATA = 4
};
	

enum DEVICE_TYPE {
	TEMPERATURE_HUMIDITY_SENSOR = 1,
	TEMPERATURE_SENSOR = 2,
	MOISTURE_SENSOR = 3,
	MOTION_DETECTOR = 4,
	DISTANCE_SENSOR = 5,
	ELECTRICITY_PULSE_DETECTOR = 6,
	RELAY = 7
	};
	
enum SOURCE_BUS {
	BUS_TWIM0 = 1,
	BUS_TWIM1 = 2,
	BUS_TWIM2 = 3,
	BUS_TWIM3 = 4,
	GPIO_EXT1_5 = 5,
	GPIO_EXT1_6 = 6,
	GPIO_EXT2_5 = 7,
	GPIO_EXT2_6 = 8,
	GPIO_EXT2_10 = 9,
	GPIO_EXT3_5 = 10,
	GPIO_EXT3_6 = 11,
	GPIO_EXT3_10 = 12,
	GPIO_EXT3_15 = 13,
	GPIO_EXT4_5 = 14,
	GPIO_EXT4_6 = 15,
	GPIO_EXT4_9 = 16,
	GPIO_EXT4_10 = 17,
	GPIO_EXT4_15 = 18,
	ADCIFE_0 = 16,
	ADCIFE_1 = 17,
	ADCIFE_2 = 18,
	ADCIFE_3 = 19,
	ADCIFE_4 = 20,
	ADCIFE_5 = 21,
	ADCIFE_6 = 22,
	ADCIFE_7 = 23
	};
	
enum GPIO_TRIGGER_EDGE_MODE {
	GPIO_TRIGGER_BOTH_EDGE = 0,
	GPIO_TRIGGER_RISING_EDGE = 1,
	GPIO_TRIGGER_FALLING_EDGE = 2
};
		
typedef struct {
	int data_type;
	int device_type;
	int source_bus;
	const char* content_data; 
} mcu_header;

#endif //MCUDATATYPES_H_